### ISSUE TITLE
encryptedContent.split is not a function

### ISSUE THREAD

**Issue by svipas** [perry-mitchell/iocane#15]
Hello,

I get this error:
```
TypeError: encryptedContent.split is not a function
    at Object.unpackEncryptedContent (/home/svipben/Documents/RNM-client/node_modules/iocane/source/packers.js:15:43)
    at Object.decryptWithPassword (/home/svipben/Documents/RNM-client/node_modules/iocane/source/crypto.js:93:43)
    at Object.<anonymous> (/home/svipben/Documents/RNM-client/test.js:11:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
```

JS file:
```
const crypto = require('iocane').crypto;

const encrypted = async (data, password) => {
  const encryptWithPassword = await crypto.encryptWithPassword(data, password);
  console.log(encryptWithPassword);
};

const enc = encrypted('testtest', 'svipben');

const decrypted = async (data, password) => {
  const decryptWithPassword = await crypto.decryptWithPassword(data, password);
  console.log(decryptWithPassword);
};

decrypted(enc, 'svipben');
```

**Comment by perry-mitchell** [comment]
Hi @svipben - Could you please share the iocane version you have installed? I get it working by rewriting your example a bit:

```javascript
const { encryptWithPassword, decryptWithPassword } = require('iocane').crypto;

(async function() {

	const enc = await encryptWithPassword("testtest", "svipben");

	console.log(enc);

	const dec = await decryptWithPassword(enc, "svipben");

	console.log(dec);

})();
```

There was something funny with your async/awaits.

I get the following output:

```
t9Tn548oyLbAYSwq+4URGA==$293e7b5926178b6ad182d39d64cedb3d$058c38d500f9$7bb357eeb63871167183b1133bc9fec264cef1d386de6e13f1ccacef74edc3e0$246665
testtest
```

**Comment by svipas** [comment]
@perry-mitchell ~Latest version of `iocane`. I see I forgot to include return in my both async functions, but even with that it doesn't works. I'm still struggling how to implement correctly async with promises, maybe you can tell me how to split into 2 functions instead of 1 like you did in your example. I always getting `Promise { <pending> }`. Sorry for this issue, I was thinking it's this package problem...~ Okey, I get the thing, sorry for this issue, it can be closed.

**Comment by perry-mitchell** [comment]
@svipben Glad you got it worked out! I'm not an expert at async/await patterns, but it looks like it's all in the context that you call the async functions from. Best of luck.

**Comment by svipas** [comment]
@perry-mitchell Thank you!
